# Nhúng toàn bộ tệp trong web/ và schema/ thành một tệp .cpp duy nhất.
#   -DTTD_SOURCE_DIR=...  -DTTD_GENERATED_DIR=...

if(NOT TTD_SOURCE_DIR OR NOT TTD_GENERATED_DIR)
    message(FATAL_ERROR "Thiếu TTD_SOURCE_DIR hoặc TTD_GENERATED_DIR")
endif()

file(MAKE_DIRECTORY "${TTD_GENERATED_DIR}")

set(_files "")
file(GLOB_RECURSE _web  RELATIVE "${TTD_SOURCE_DIR}/web"    "${TTD_SOURCE_DIR}/web/*")
file(GLOB_RECURSE _schm RELATIVE "${TTD_SOURCE_DIR}/schema" "${TTD_SOURCE_DIR}/schema/*.tl")

set(_body "")
set(_table "")
set(_index 0)

foreach(_rel IN LISTS _web)
    set(_abs "${TTD_SOURCE_DIR}/web/${_rel}")
    if(IS_DIRECTORY "${_abs}")
        continue()
    endif()
    file(READ "${_abs}" _hex HEX)
    string(LENGTH "${_hex}" _hexlen)
    math(EXPR _len "${_hexlen} / 2")
    string(REGEX REPLACE "(..)" "0x\\1," _bytes "${_hex}")
    string(APPEND _body "static const unsigned char kAsset${_index}[] = {${_bytes}0x00}\;\n")
    string(APPEND _table "  {\"${_rel}\", kAsset${_index}, ${_len}},\n")
    math(EXPR _index "${_index} + 1")
endforeach()

foreach(_rel IN LISTS _schm)
    set(_abs "${TTD_SOURCE_DIR}/schema/${_rel}")
    if(IS_DIRECTORY "${_abs}")
        continue()
    endif()
    file(READ "${_abs}" _hex HEX)
    string(LENGTH "${_hex}" _hexlen)
    math(EXPR _len "${_hexlen} / 2")
    string(REGEX REPLACE "(..)" "0x\\1," _bytes "${_hex}")
    string(APPEND _body "static const unsigned char kAsset${_index}[] = {${_bytes}0x00}\;\n")
    string(APPEND _table "  {\"schema/${_rel}\", kAsset${_index}, ${_len}},\n")
    math(EXPR _index "${_index} + 1")
endforeach()

set(_content "// Tệp này được sinh tự động từ web/ và schema/ — đừng sửa tay.\n")
string(APPEND _content "#include <cstddef>\n\n")
string(APPEND _content "namespace ttd {\nnamespace assets {\n\n")
string(APPEND _content "struct EmbeddedAsset { const char* path\; const unsigned char* data\; size_t size\; }\;\n\n")
string(APPEND _content "${_body}\n")
string(APPEND _content "static const EmbeddedAsset kAssets[] = {\n${_table}  {nullptr, nullptr, 0}\n}\;\n\n")
string(APPEND _content "const EmbeddedAsset* embeddedAssetTable() { return kAssets\; }\n")
string(APPEND _content "size_t embeddedAssetCount() { return ${_index}\; }\n\n")
string(APPEND _content "} // namespace assets\n} // namespace ttd\n")

set(_out "${TTD_GENERATED_DIR}/embedded_assets.cpp")
set(_old "")
if(EXISTS "${_out}")
    file(READ "${_out}" _old)
endif()
if(NOT _old STREQUAL _content)
    file(WRITE "${_out}" "${_content}")
endif()

message(STATUS "Đã nhúng ${_index} tài nguyên")
